query AlloySearch(
  $q: String!
  $locale: [Locales!]
  $limit: Int = 20
  $pinnedCollectionId: String
) {
  Content(
    where: {
      _or: [
        { _fulltext: { match: $q, synonyms: ONE } }
        { Name: { match: $q, boost: 5, synonyms: ONE } }
      ]
    }
    locale: $locale
    limit: $limit
    orderBy: { _ranking: SEMANTIC, _minimumScore: 2.5 }
    usePinned: { phrase: $q, collectionId: $pinnedCollectionId }
  ) {
    items {
      Name
      ContentType
      _score
      _fulltext
    }
  }
}
